nav_identity_bridge:
  ros__parameters:
    use_sim_time: true
    map_frame: map
    nav_map_frame: map_nav
    nav_odom_frame: odom_nav
    publish_rate: 20.0

map_to_baselink_node:
  ros__parameters:
    use_sim_time: true
    odom_frame: odom
    odom_nav_frame: odom_nav
    map_frame: map
    base_frame: odin1_base_link
    output_topic: /map_base_pose
    publish_tf: true
    if_nav2: true
    if_on_robot: true
    tf_child_frame: map_corrected_base_link
    odin1_camera_frame: odin1_camera_link
    mid360_camera_frame: livox_frame
    publish_rate: 20.0
    tf_baselink_odin1: [-0.02897, 0.11458, 0.24799, 0.0, 0.0, 0.7071068, 0.7071068]
    tf_baselink_mid360: [0.0025, -0.13509, 0.29325, 0.0, 0.382684, -0.923879, 0.0]

lidar_filter_node:
  ros__parameters:
    use_sim_time: true
    input_topic: /cloud_nav2_raw
    output_topic: /cloud_nav2
    crop_frame: map_corrected_base_link
    min_x: -0.3
    max_x: 0.3
    min_y: -0.3
    max_y: 0.3
    min_z: -0.1
    max_z: 0.6
    negative: true
    use_voxel: false
    leaf_size: 0.05

odin1_filter_node:
  ros__parameters:
    use_sim_time: true
    input_topic: /odin1/cloud_slam
    output_topic: /odin1/cloud_slam_filter
    z_threshold: 1.0
    leaf_size: 0.05

cloud_frame_transformer:
  ros__parameters:
    use_sim_time: true
    input_topic: /odin1/cloud_slam_filter
    mid360_pointcloud_topic: livox/lidar
    mid360_frame: livox_frame
    output_topic: /cloud_nav2_raw
    target_frame: odom_nav

map_publish:
  ros__parameters:
    use_sim_time: true
    yaml_path: /home/xli/catkin_ws/src/sentry_description/maps/cad_map.yaml
    #地图yaml文件路径,默认/home/xli/catkin_ws/src/Sentry-Nav/map/map_nav.yaml
    topic_name: /map
    frame_id: map_nav
    publish_period: 1.0

rviz2_savedmap_nav:
  ros__parameters:
    use_sim_time: true
